version: "3"
services:
  surrealdb:
    restart: always
    image: surrealdb/surrealdb:${SOFTWARE_VERSION_TAG}
    user: root
    ports:
      - "172.17.0.1:27912:8000"
    env_file:
      - ./.env
    command: start
    volumes:
      - ./db:/db
